image:
  tag: v1beta2-1.2.3-3.1.1
serviceAccounts:
  spark:
    create: false
  sparkoperator:
    create: true  
metrics:
# -- Disable prometheus metric scraping
  enable: false
webhook:
  enable: true
  port: 443